In [76]:
import pandas as pd
import numpy as np
import json as js
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image

import warnings
warnings.simplefilter('ignore')

--NotebookApp.iopub_data_rate_limit=1000000000

# будем отображать графики прямо в jupyter'e
%pylab inline
#графики в svg выглядят более четкими
%config InlineBackend.figure_format = 'svg' 

#увеличим дефолтный размер графиков
from pylab import rcParams
rcParams['figure.figsize'] = 8,5

SyntaxError: can't assign to operator (<ipython-input-76-1461677e4a8e>, line 11)

In [40]:
raw_pl=pd.read_csv('players.csv')

In [41]:
raw_pl.head(2)

,Unnamed: 0,Player,height,weight,collage,born,birth_city,birth_state
0,0,Curly Armstrong,180.0,77.0,Indiana University,1918.0,NaN,NaN
1,1,Cliff Barker,188.0,83.0,University of Kentucky,1921.0,Yorktown,Indiana

In [42]:
raw_st=pd.read_csv('Seasons_Stats.csv')

In [43]:
raw_st.head(2)

,Unnamed: 0,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,...,0.705,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0
1,1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,...,0.708,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0

In [44]:
raw_st.describe()
raw_st['Player_ind']=1

In [45]:
raw_st.head()

,Unnamed: 0,Year,Player,Pos,Age,Tm,G,GS,MP,PER,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Player_ind
0,0,1950.0,Curly Armstrong,G-F,31.0,FTW,63.0,NaN,NaN,NaN,...,NaN,NaN,NaN,176.0,NaN,NaN,NaN,217.0,458.0,1
1,1,1950.0,Cliff Barker,SG,29.0,INO,49.0,NaN,NaN,NaN,...,NaN,NaN,NaN,109.0,NaN,NaN,NaN,99.0,279.0,1
2,2,1950.0,Leo Barnhorst,SF,25.0,CHS,67.0,NaN,NaN,NaN,...,NaN,NaN,NaN,140.0,NaN,NaN,NaN,192.0,438.0,1
3,3,1950.0,Ed Bartels,F,24.0,TOT,15.0,NaN,NaN,NaN,...,NaN,NaN,NaN,20.0,NaN,NaN,NaN,29.0,63.0,1
4,4,1950.0,Ed Bartels,F,24.0,DNN,13.0,NaN,NaN,NaN,...,NaN,NaN,NaN,20.0,NaN,NaN,NaN,27.0,59.0,1

In [91]:
useful_cols = ['Tm','Age','FG%','MP','PER']
base = raw_st[useful_cols]
base.info()
base.dropna(inplace=True)
base.info()
#sns.pairplot(base)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24691 entries, 0 to 24690
Data columns (total 5 columns):
Tm     24624 non-null object
Age    24616 non-null float64
FG%    24525 non-null float64
MP     24138 non-null float64
PER    24101 non-null float64
dtypes: float64(4), object(1)
memory usage: 964.6+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 23999 entries, 488 to 24690
Data columns (total 5 columns):
Tm     23999 non-null object
Age    23999 non-null float64
FG%    23999 non-null float64
MP     23999 non-null float64
PER    23999 non-null float64
dtypes: float64(4), object(1)
memory usage: 1.1+ MB

In [95]:
base.groupby('Tm').head()
#sns.scatter(base.groupby('Age')['PER'].median())
#sns.regplot(base['Age'],base.groupby('Age')['PER'].median())

        Tm   Age    FG%      MP   PER
488    PHW  23.0  0.448  2939.0  25.5
489    INO  31.0  0.298   494.0  10.8
490    BLB  28.0  0.338  2014.0  15.8
491    INO  27.0  0.389  2344.0  15.9
492    MLH  22.0  0.273    55.0   7.8
493    MLH  30.0  0.194   117.0   1.1
494    PHW  27.0  0.359  1192.0  10.9
495    NYK  24.0  0.387  1440.0  12.8
496    MLH  26.0  0.299  1982.0  12.4
497    BOS  26.0  0.369  1324.0  12.4
498    FTW  28.0  0.352  2672.0  14.8
499    PHW  22.0  0.349   141.0   6.1
500    PHW  26.0  0.404  1126.0  10.2
501    TOT  27.0  0.269   514.0   5.5
502    FTW  27.0  0.240   245.0   1.9
503    MLH  27.0  0.296   269.0   8.8
504    SYR  26.0  0.344   937.0   9.4
505    BLB  24.0  0.315  1594.0  10.2
506    SYR  34.0  0.354   850.0  21.9
507    MLH  24.0  0.302   374.0  10.7
508    NYK  29.0  0.335  2101.0  16.4
509    FTW  30.0  0.308  1120.0  10.4
510    ROC  27.0  0.415  2606.0  15.5
511    BOS  25.0  0.361  1976.0  12.6
512    BOS  23.0  0.369  2681.0  21.4
513    TOT  27.0  0.351   783.0  12.3
514    INO  27.0  0.400    23.0  12.7
516    PHW  26.0  0.368   112.0  10.3
517    ROC  32.0  0.383  2394.0  17.4
519    BOS  25.0  0.294   440.0   9.6
...    ...   ...    ...     ...   ...
17077  CHA  31.0  0.327   201.0   8.8
17080  CHA  26.0  0.485   271.0  14.8
17132  CHA  24.0  0.381  1791.0  10.4
17151  CHA  25.0  0.512  2276.0  16.1
17175  CHA  24.0  0.389   430.0  14.7
17668  NOK  27.0  0.571   570.0  14.1
17704  NOK  20.0  0.400   268.0   9.1
17738  NOK  36.0  0.461  2380.0  12.7
17749  NOK  26.0  0.406  1875.0  10.8
17767  NOK  27.0  0.413  2019.0  16.1
19367  OKC  34.0  0.291   297.0   5.1
19452  OKC  28.0  0.568  1831.0  14.8
19506  OKC  20.0  0.476  2885.0  20.8
19552  OKC  22.0  0.446  2873.0  13.9
19581  OKC  23.0  1.000     2.0  88.3
21737  BRK  26.0  0.512  1555.0  21.9
21739  BRK  32.0  0.380  1408.0   6.7
21754  BRK  24.0  0.463   912.0  13.5
21774  BRK  29.0  0.286   100.0   7.0
21835  BRK  32.0  0.479  1967.0  12.8
22261  NOP  25.0  0.546   951.0  14.6
22269  NOP  23.0  0.474  2045.0  13.2
22271  NOP  31.0  0.500   184.0   9.2
22276  NOP  25.0  0.438   795.0  18.8
22293  NOP  24.0  0.390   473.0  12.1
22920  CHO  22.0  0.543  1243.0  15.2
23005  CHO  23.0  0.458   135.0  16.1
23107  CHO  22.0  0.323   687.0   9.0
23125  CHO  27.0  0.437  2315.0  13.2
23155  CHO  30.0  0.481  1992.0  19.7

[305 rows x 5 columns]

In [50]:
raw_st.info()
raw_st.dropna()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24691 entries, 0 to 24690
Data columns (total 54 columns):
Unnamed: 0    24691 non-null int64
Year          24624 non-null float64
Player        24624 non-null object
Pos           24624 non-null object
Age           24616 non-null float64
Tm            24624 non-null object
G             24624 non-null float64
GS            18233 non-null float64
MP            24138 non-null float64
PER           24101 non-null float64
TS%           24538 non-null float64
3PAr          18839 non-null float64
FTr           24525 non-null float64
ORB%          20792 non-null float64
DRB%          20792 non-null float64
TRB%          21571 non-null float64
AST%          22555 non-null float64
STL%          20792 non-null float64
BLK%          20792 non-null float64
TOV%          19582 non-null float64
USG%          19640 non-null float64
blanl         0 non-null float64
OWS           24585 non-null float64
DWS           24585 non-null float64
WS            24585 non-null float64
WS/48         24101 non-null float64
blank2        0 non-null float64
OBPM          20797 non-null float64
DBPM          20797 non-null float64
BPM           20797 non-null float64
VORP          20797 non-null float64
FG            24624 non-null float64
FGA           24624 non-null float64
FG%           24525 non-null float64
3P            18927 non-null float64
3PA           18927 non-null float64
3P%           15416 non-null float64
2P            24624 non-null float64
2PA           24624 non-null float64
2P%           24496 non-null float64
eFG%          24525 non-null float64
FT            24624 non-null float64
FTA           24624 non-null float64
FT%           23766 non-null float64
ORB           20797 non-null float64
DRB           20797 non-null float64
TRB           24312 non-null float64
AST           24624 non-null float64
STL           20797 non-null float64
BLK           20797 non-null float64
TOV           19645 non-null float64
PF            24624 non-null float64
PTS           24624 non-null float64
Player_ind    24691 non-null int64
dtypes: float64(49), int64(2), object(3)
memory usage: 10.2+ MB

Empty DataFrame
Columns: [Unnamed: 0, Year, Player, Pos, Age, Tm, G, GS, MP, PER, TS%, 3PAr, FTr, ORB%, DRB%, TRB%, AST%, STL%, BLK%, TOV%, USG%, blanl, OWS, DWS, WS, WS/48, blank2, OBPM, DBPM, BPM, VORP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, Player_ind]
Index: []

[0 rows x 54 columns]

In [47]:
plt.plot(over_age_PER)